Mkframework 4.133 hello world prepare
phpbenchmarks/mkframework pull request #1
Opened 2019-05-30 12:48 UTC by imikado

premiere version validée

2019-05-30 15:55 UTC, imikado commented
ajout ficheirs manquants + fichier readme updaté

2019-06-23 20:11 UTC, steevanb requested changes

2019-06-23 20:11 UTC, steevanb commented on .phpbenchmarks/AbstractComponentConfiguration.php
> +<?php
vu la syntaxe du fichier, je ne suis pas sûr que le kit de benchmark ait fonctionné pour PHP 5.6. tu peux tester de lancer `phpbench benchmark:validate` ?

2019-06-23 20:11 UTC, steevanb commented on .phpbenchmarks/initBenchmark.sh
> +#!/usr/bin/env bash
aucun cache à vider avant de lancer un benchmark ? il n'y aucune autre opération d'initialisation que `composer install` ?

2019-06-23 20:11 UTC, steevanb commented on business/business_abstract.php
> +<?php
je ne comprend pas à quoi sert cette classe pour le benchmark Hello World ?

2019-06-23 20:11 UTC, steevanb commented on composer.lock
> +{
j'ai du oublier de mettre le `composer.lock` dans `.gitignore`. ce fichier ne doit pas être commité, vu que j'utilise ceux qui sont dans le répertoire `.phpbenchmarks`.

2019-06-23 20:11 UTC, steevanb commented on conf/connexion.ini.php
> +;<?php die()?>
ce fichier est vraiment indispensable, sachant que le benchmark Hello World n'a pas d'accès à une BDD ? ça va ralentir tes résultats.

2024-11-22 10:03 UTC, closed without merging